{{- if .Values.notification.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: notification-sender
  labels:
    {{- include "myampix.labels" . | nindent 4 }}
    {{- include "myampix.selectorLabels" (dict "root" . "name" "notification-sender" "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "myampix.selectorLabels" (dict "root" . "name" "notification-sender" "component" "api") | nindent 4 }}
{{- end }}
