{{- if .Values.purchase.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mobile-purchase-api
  labels:
    {{- include "myampix.labels" . | nindent 4 }}
    {{- include "myampix.selectorLabels" (dict "root" . "name" "mobile-purchase" "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.purchase.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "myampix.selectorLabels" (dict "root" . "name" "mobile-purchase" "component" "api") | nindent 6 }}
{{- end }}
